// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVO2zhHew6EuDr3yNPvUK0PdVOgWo8p_g',
    appId: '1:906400327488:android:667de87715d89fd291fca5',
    messagingSenderId: '906400327488',
    projectId: 'fluttergatopedia',
    databaseURL: 'https://fluttergatopedia-default-rtdb.firebaseio.com',
    storageBucket: 'fluttergatopedia.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKglLyclrqKhfYgDl6SWdTZvha09Jj768',
    appId: '1:906400327488:web:32c39cf107be006691fca5',
    messagingSenderId: '906400327488',
    projectId: 'fluttergatopedia',
    authDomain: 'fluttergatopedia.firebaseapp.com',
    databaseURL: 'https://fluttergatopedia-default-rtdb.firebaseio.com',
    storageBucket: 'fluttergatopedia.appspot.com',
    measurementId: 'G-XD3EN1YDVE',
  );
}
